name: Auto Merge

on:
  workflow_run:
    workflows:
      - "Build Changes"
    types:
      - completed

jobs:
  automerge:
    name: Auto merge request
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
