#name: Auto Merge
#
#on:
#  pull_request:
#    branches:
#      - main
#    types:
#      - labeled
#      - unlabeled
#      - synchronize
#      - opened
#      - edited
#      - ready_for_review
#      - reopened
#      - unlocked
#  check_suite:
#    types:
#      - completed
#  status: {}
#
#jobs:
#  automerge:
#    name: Auto merge request
#    runs-on: ubuntu-latest
#    steps:
#      - id: automerge
#        name: automerge
#        uses: "pascalgn/automerge-action@v0.15.3"
#        env:
#          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
