name: Build

on:
  push:
    branches:
      - main
      - develop

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml

  coverage:
    uses: ./.github/workflows/coverage.yml

  deploy-docker:
    uses: ./github/workflows/deploy_docker.yml