name: Build

on:
  push:
    branches:
      - main
      - develop

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml

  test:
    name: Test
    uses: ./.github/workflows/test.yml

  coverage:
    name: Coverage
    uses: ./.github/workflows/coverage.yml

  deploy-docker:
    name: Deploy Docker
    uses: ./.github/workflows/deploy_docker.yml