name: Build Changes

on:
  push:
    branches:
      - develop

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml

  dependency-check:
    uses: ./.github/workflows/dependency_check.yml

  pull-request:
    needs:
      - lint
      - test
      - dependency-check
    uses: ./.github/workflows/pull_request.yml