name: Docker Deploy

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      app_name:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  deploy-docker:
    name: Deploy Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ inputs.username }}
          password: ${{ secrets.token }}

      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ inputs.username }}/${{ inputs.app_name }}:latest
            ${{ inputs.username }}/${{ inputs.app_name }}:${{ github.run_number }}