name: Lint

on:
  push:
    branches:
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      #      - name: Setup cache
      #        uses: actions/cache@v3
      #        with:
      #          path: |
      #            ~/.cache/go-build
      #            ~/go/pkg/mod
      #          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      #          restore-keys: |
      #            ${{ runner.os }}-go-

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Checkout code
        uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest