name: Test

on:
  workflow_call:

jobs:
  test:
    name: Test
    #    strategy:
    #      matrix:
    #        go-version: [ 1.19 ]
    #        platform: [ ubuntu-latest, macos-latest, windows-latest ]
    #    runs-on: ${{ matrix.platform }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Install dependencies
        run: go mod download

      - name: Run unit test
        run: go test -v ./...